export interface TemplateChecklistItem {
    z: string;      // zone: gar, lixo, dry
    c: string;      // category
    tp: 'exec' | 'bim';  // type/mode
    tg: string;     // discipline tag: ARQ, EST, etc.
    txt: string;    // text description
    obs?: string;   // observations / reference
}

export const DISC: Record<string, { n: string; h: string }> = {
    AIT: { n: "Arq. Interiores", h: "#646464" },
    ARQ: { n: "Arquitetura", h: "#FF8000" },
    AUT: { n: "Automação", h: "#C49A20" },
    CLI: { n: "Climatização", h: "#3382D0" },
    ELE: { n: "Elétrica", h: "#3A985B" },
    EST: { n: "Estrutura", h: "#7070CC" },
    GER: { n: "Gerenciadora", h: "#CC5555" },
    HID: { n: "Hidráulica", h: "#3A9AC0" },
    LMT: { n: "Luminotécnico", h: "#B03880" },
    PCI: { n: "Prev. Incêndio", h: "#CC0000" },
    PLE: { n: "Proj. Legal", h: "#804000" },
    PSG: { n: "Paisagismo", h: "#5A8820" },
    FTV: { n: "Fotovoltaico", h: "#800080" },
    STM: { n: "Estr. Metálica", h: "#8A2A00" },
    TEL: { n: "Telecomunicações", h: "#2A5A90" },
    DRY: { n: "Drywall", h: "#A05A20" },
    IMP: { n: "Impermeabiliz.", h: "#6A4010" },
    BIM: { n: "Coord. BIM", h: "#1A4080" },
    MEP: { n: "MEP / Compat.", h: "#305060" },
    MEC: { n: "Mecânica", h: "#3A6050" },
    SEG: { n: "Segurança/CFTV", h: "#333333" }
};

export const TEMPLATES: TemplateChecklistItem[] = [
    // Garagem (gar) - exec
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Dimensões exatas das vagas padrão", obs: "Mín. 2,30m × 4,50m — verificar código de obras" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Dimensões das vagas PCD", obs: "3,50m × 5,00m + espaço de transferência lateral" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Vagas de moto e utilitário dimensionadas" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Largura das faixas de circulação", obs: "Mín. 5,00m sentido único; 7,00m dupla mão" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Raios de giro das curvas cotados" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Recuos entre vagas e pilares cotados" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Largura e comprimento da rampa cotados" },
    { z: "gar", c: "Cotas e Geometria", tp: "exec", tg: "ARQ", txt: "Posição e cota da cancela / portão de acesso" },
    { z: "gar", c: "Tabela de Vagas", tp: "exec", tg: "ARQ", txt: "Tabela completa: número, tipo, unidade vinculada, pavimento", obs: "Padrão / PCD / Moto / Utilitário / Visitante" },
    { z: "gar", c: "Tabela de Vagas", tp: "exec", tg: "ARQ", txt: "Numeração de cada vaga na planta e na tabela" },
    { z: "gar", c: "Tabela de Vagas", tp: "exec", tg: "ARQ", txt: "Quadro-resumo: total por tipo e total geral" },
    { z: "gar", c: "Tabela de Vagas", tp: "exec", tg: "ARQ", txt: "Vagas de visitante e paraciclos locados" },
    { z: "gar", c: "Tabela de Vagas", tp: "exec", tg: "ARQ", txt: "Conformidade taxa mínima PCD — NBR 9050 + código municipal" },
    { z: "gar", c: "Níveis e Caimentos", tp: "exec", tg: "ARQ", txt: "Cotas de nível em osso e acabado — todos os setores" },
    { z: "gar", c: "Níveis e Caimentos", tp: "exec", tg: "ARQ", txt: "Inclinação da rampa indicada (%)", obs: "Máx. 20% fechada; 15% descoberta — NBR 9050" },
    { z: "gar", c: "Níveis e Caimentos", tp: "exec", tg: "ARQ", txt: "Curvas de transição superior e inferior da rampa" },
    { z: "gar", c: "Níveis e Caimentos", tp: "exec", tg: "ARQ", txt: "Caimento de piso com setas e % por setor", obs: "Mín. 0,5% → ralos e grelhas" },
    { z: "gar", c: "Níveis e Caimentos", tp: "exec", tg: "ARQ", txt: "Pé-direito livre verificado — pontos críticos", obs: "Mín. 2,20m — indicar abaixo de vigas e dutos" },
    { z: "gar", c: "Estrutura", tp: "exec", tg: "EST", txt: "Locação precisa dos pilares — dimensões reais + cotas" },
    { z: "gar", c: "Estrutura", tp: "exec", tg: "EST", txt: "Paredes estruturais e muros de arrimo representados" },
    { z: "gar", c: "Estrutura", tp: "exec", tg: "EST", txt: "Interface pilar × bloco / sapata geometricamente cotada" },
    { z: "gar", c: "Estrutura", tp: "exec", tg: "IMP", txt: "Impermeabilização do muro de arrimo detalhada" },
    { z: "gar", c: "Pintura de Pilares", tp: "exec", tg: "ARQ", txt: "Especificação completa da tinta — tipo, cor e brilho", obs: "Esmalte, epóxi ou tinta borracha" },
    { z: "gar", c: "Pintura de Pilares", tp: "exec", tg: "ARQ", txt: "Faixas de atenção preto/amarelo nos pilares de circulação" },
    { z: "gar", c: "Pintura de Pilares", tp: "exec", tg: "ARQ", txt: "Numeração dos pilares — fonte, tamanho, posição" },
    { z: "gar", c: "Pintura de Pilares", tp: "exec", tg: "ARQ", txt: "Tinta retrorrefletiva nos pilares em área de manobra" },
    { z: "gar", c: "Pintura de Pilares", tp: "exec", tg: "ARQ", txt: "Cantoneiras protetoras nos pilares de ângulo" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "Demarcação das faixas de vagas — especificar tinta e demãos" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "Zebrado PCD e rotas de pedestres", obs: "Faixas preto/amarelo 45°" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "Setas direcionais de fluxo no piso" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "Faixa de pedestres em cor contrastante" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "Numeração de vagas e símbolo PCD no piso — NBR 9050" },
    { z: "gar", c: "Sinalização Horizontal", tp: "exec", tg: "ARQ", txt: "STOP pintado antes da rampa / saída" },
    { z: "gar", c: "Sinalização Vertical", tp: "exec", tg: "ARQ", txt: "Placa de altura máxima na entrada — cota exata de gabarito" },
    { z: "gar", c: "Sinalização Vertical", tp: "exec", tg: "ARQ", txt: "Placas de limite de velocidade, sentido e saídas" },
    { z: "gar", c: "Sinalização Vertical", tp: "exec", tg: "ARQ", txt: "Placa de reserva PCD — altura regulamentar" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Rampa — corte longitudinal e transversal completo" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Guarda-corpo da rampa — seção, ancoragem, norma" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Portão / cancela — tipo, vão, folha, acionamento" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "HID", txt: "Calha de drenagem da rampa — seção, grelha, material" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Bate-rodas — seção, material, fixação, cor" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Limitadores de altura — perfil, fixação, sinalização" },
    { z: "gar", c: "Detalhamentos", tp: "exec", tg: "ARQ", txt: "Junta de dilatação do piso — perfil e material" },
    { z: "gar", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Sprinklers — raio de cobertura e cota de instalação" },
    { z: "gar", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Hidrantes e extintores — posição, tipo, acessibilidade" },
    { z: "gar", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Iluminação de emergência — circuito, autonomia e cota" },
    { z: "gar", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Rota de fuga sinalizada — horizontal e vertical" },
    { z: "gar", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Detector de CO/fumaça — posição e cota" },
    { z: "gar", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Ralos secos, sifonados, grelhas e calhas — posição e DN" },
    { z: "gar", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Caimento de piso por setor direcionado aos ralos" },
    { z: "gar", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Sistema de recalque — bombas e registros locados" },
    { z: "gar", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Ramal pluvial da rampa — calha ou ralo lateral" },
    { z: "gar", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Quadros de força e distribuição — posição na planta" },
    { z: "gar", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Luminárias e iluminação de emergência locadas" },
    { z: "gar", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Infraestrutura para carregadores VE — conduite e pontos" },
    { z: "gar", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Tomadas de uso geral com IP adequado" },
    { z: "gar", c: "Compat. Telecom", tp: "exec", tg: "TEL", txt: "Câmeras CFTV — posição, ângulo, cota" },
    { z: "gar", c: "Compat. Telecom", tp: "exec", tg: "TEL", txt: "Interfone e controle de acesso — leitores de tag" },
    { z: "gar", c: "Compat. Telecom", tp: "exec", tg: "AUT", txt: "Cancela integrada ao sistema de automação predial" },
    { z: "gar", c: "Compat. Mecânica", tp: "exec", tg: "MEC", txt: "Dutos de exaustão mecânica — pé-direito livre" },
    { z: "gar", c: "Compat. Mecânica", tp: "exec", tg: "MEC", txt: "Ventiladores de exaustão — clearance de manutenção" },
    { z: "gar", c: "Compat. Mecânica", tp: "exec", tg: "MEC", txt: "Sensor CO/NOx — posição e cota" },
    { z: "gar", c: "Acabamentos", tp: "exec", tg: "ARQ", txt: "Especificação completa do piso", obs: "Concreto desempenado, epóxi, polido ou intertravado" },
    { z: "gar", c: "Acabamentos", tp: "exec", tg: "ARQ", txt: "Piso da rampa antiderrapante — coeficiente de atrito mínimo" },
    { z: "gar", c: "Acabamentos", tp: "exec", tg: "ARQ", txt: "Juntas de dilatação — espaçamento, perfil, material" },
    { z: "gar", c: "Acabamentos", tp: "exec", tg: "ARQ", txt: "Pintura de paredes e teto — sistema e cor" },
    
    // Garagem (gar) - bim
    { z: "gar", c: "Geometria e Vagas", tp: "bim", tg: "BIM", txt: "Vagas como elementos paramétricos com tipo, número, unidade" },
    { z: "gar", c: "Geometria e Vagas", tp: "bim", tg: "BIM", txt: "Tabela de vagas extraída do modelo — sem tabela manual" },
    { z: "gar", c: "Geometria e Vagas", tp: "bim", tg: "BIM", txt: "Cancela / portão modelado com folha e caixa de acionamento" },
    { z: "gar", c: "Geometria e Vagas", tp: "bim", tg: "BIM", txt: "Bate-rodas como famílias com fabricante e dimensões" },
    { z: "gar", c: "Pilares e Sinalização", tp: "bim", tg: "BIM", txt: "Pilares com material de pintura — extrair m² por pilar" },
    { z: "gar", c: "Pilares e Sinalização", tp: "bim", tg: "BIM", txt: "Faixas de atenção: piso 2mm + material 'Tinta Epóxi Amarela'" },
    { z: "gar", c: "Pilares e Sinalização", tp: "bim", tg: "BIM", txt: "Sinalização horizontal: piso 2mm por tipo de tinta", obs: "Amarela/Branca/Azul PCD — m² por material" },
    { z: "gar", c: "Pilares e Sinalização", tp: "bim", tg: "BIM", txt: "Cantoneiras como famílias com comprimento parametrizado" },
    { z: "gar", c: "Suportes MEP", tp: "bim", tg: "MEP", txt: "Tirantes e abraçadeiras de tubulações modelados na laje" },
    { z: "gar", c: "Suportes MEP", tp: "bim", tg: "MEP", txt: "Clearance 1,0m de frente dos painéis elétricos modelado" },
    { z: "gar", c: "Suportes MEP", tp: "bim", tg: "MEP", txt: "Clearance de manutenção dos ventiladores modelado" },
    { z: "gar", c: "Caimentos e Juntas", tp: "bim", tg: "EST", txt: "Contrapiso com caimento real via shape editing", obs: "Altera volume de concreto no quantitativo" },
    { z: "gar", c: "Caimentos e Juntas", tp: "bim", tg: "EST", txt: "Rampa com inclinação real — juntas de dilatação modeladas" },
    { z: "gar", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Extintores: tipo, capacidade, fabricante como instâncias" },
    { z: "gar", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Câmeras CFTV com ângulo de cobertura parametrizado" },
    { z: "gar", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Schedule de materiais de piso por tipo em m²" },

    // Casa de Lixo (lixo) - exec
    { z: "lixo", c: "Layout", tp: "exec", tg: "ARQ", txt: "Dimensões internas com medidas reais dos contêineres adotados" },
    { z: "lixo", c: "Layout", tp: "exec", tg: "ARQ", txt: "Área de circulação e manobra para retirada dos contêineres" },
    { z: "lixo", c: "Layout", tp: "exec", tg: "ARQ", txt: "Separação orgânico × reciclável — divisória ou faixa" },
    { z: "lixo", c: "Layout", tp: "exec", tg: "ARQ", txt: "Número e capacidade dos contêineres indicados na planta" },
    { z: "lixo", c: "Layout", tp: "exec", tg: "ARQ", txt: "Rota de acesso dos coletores até a via pública" },
    { z: "lixo", c: "Revestimentos", tp: "exec", tg: "ARQ", txt: "Cerâmica piso e paredes até o teto — PEI mín. 4" },
    { z: "lixo", c: "Revestimentos", tp: "exec", tg: "IMP", txt: "Impermeabilização do piso com sobreposição 30cm nas paredes" },
    { z: "lixo", c: "Revestimentos", tp: "exec", tg: "ARQ", txt: "Rodapé em meia-cana especificado" },
    { z: "lixo", c: "Revestimentos", tp: "exec", tg: "ARQ", txt: "Composição exata das paredes definida", obs: "Bloco + chapisco + emboço + arg. colante + cerâmica" },
    { z: "lixo", c: "Hidrossanitário", tp: "exec", tg: "HID", txt: "Torneira de lavagem com cota de altura — 0,80m do piso" },
    { z: "lixo", c: "Hidrossanitário", tp: "exec", tg: "HID", txt: "Ralo sifonado 100mm — caimento mín. 1,5% para ralo" },
    { z: "lixo", c: "Hidrossanitário", tp: "exec", tg: "HID", txt: "Ramal de esgoto do ralo — interligado à rede (não pluvial)" },
    { z: "lixo", c: "Hidrossanitário", tp: "exec", tg: "HID", txt: "Caixa de inspeção de saída de esgoto locada" },
    { z: "lixo", c: "Esquadrias", tp: "exec", tg: "ARQ", txt: "Porta metálica — abrir para fora, veneziana fixa", obs: "Chapa galvanizada ou inox — espessura especificada" },
    { z: "lixo", c: "Esquadrias", tp: "exec", tg: "ARQ", txt: "Vão livre cotado para passagem do maior contêiner" },
    { z: "lixo", c: "Esquadrias", tp: "exec", tg: "ARQ", txt: "Batente, portal, marco — fixação na alvenaria" },
    { z: "lixo", c: "Esquadrias", tp: "exec", tg: "ARQ", txt: "Veneziana — área livre mínima calculada, tela anti-inseto" },
    { z: "lixo", c: "Proteção", tp: "exec", tg: "ARQ", txt: "Bate-macas no percurso dos contêineres" },
    { z: "lixo", c: "Proteção", tp: "exec", tg: "ARQ", txt: "Cantoneiras protetoras nas arestas — material e altura" },
    { z: "lixo", c: "Níveis", tp: "exec", tg: "ARQ", txt: "Desnível / soleira na porta — 2–5cm" },
    { z: "lixo", c: "Níveis", tp: "exec", tg: "ARQ", txt: "Cotas de nível em osso e acabado" },
    { z: "lixo", c: "Instalações", tp: "exec", tg: "ELE", txt: "Luminária IP65 — 200 lux mínimo" },
    { z: "lixo", c: "Instalações", tp: "exec", tg: "ELE", txt: "Interruptor externo — posição cotada" },
    { z: "lixo", c: "Instalações", tp: "exec", tg: "PCI", txt: "Extintor — localização e tipo" },
    { z: "lixo", c: "Instalações", tp: "exec", tg: "TEL", txt: "Câmera CFTV se exigido" },
    
    // Casa de Lixo (lixo) - bim
    { z: "lixo", c: "Conexões", tp: "bim", tg: "HID", txt: "Ralo sifonado com conector MEP ligado à rede de esgoto" },
    { z: "lixo", c: "Conexões", tp: "bim", tg: "HID", txt: "Torneira com conector MEP e ramal modelado" },
    { z: "lixo", c: "Conexões", tp: "bim", tg: "HID", txt: "Caimento real do contrapiso via shape editing" },
    { z: "lixo", c: "Esquadrias BIM", tp: "bim", tg: "ARQ", txt: "Porta metálica: batente, dobradiças, veneziana modelados" },
    { z: "lixo", c: "Esquadrias BIM", tp: "bim", tg: "ARQ", txt: "Vão livre verificado no modelo com folga real" },
    { z: "lixo", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Paredes multicamada com composição exata no tipo" },
    { z: "lixo", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Contêineres como instâncias: tipo, capacidade, fabricante" },
    { z: "lixo", c: "Quantitativos", tp: "bim", tg: "BIM", txt: "Schedule de cerâmica: m² por ambiente e por material" },

    // Drywall (dry) - exec
    { z: "dry", c: "Planta e Locação", tp: "exec", tg: "DRY", txt: "Planta de locação das paredes drywall cotadas — todos os ambientes" },
    { z: "dry", c: "Planta e Locação", tp: "exec", tg: "ARQ", txt: "Compatibilização com planta ARQ — revisão mais recente" },
    { z: "dry", c: "Planta e Locação", tp: "exec", tg: "DRY", txt: "Identificação de cada tipo de parede por código na planta" },
    { z: "dry", c: "Planta e Locação", tp: "exec", tg: "ARQ", txt: "Cota interna de todos os ambientes — área mínima verificada" },
    { z: "dry", c: "Planta e Locação", tp: "exec", tg: "DRY", txt: "Nível de piso acabado e teto por setor indicados" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "ST 98 — 1 guia + 1 montante + 1 chapa cada face = 98mm", obs: "Áreas secas — uso geral" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "ST 78 — 1 guia + 1 montante + 1 chapa cada face = 78mm", obs: "Divisórias leves internas" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "DT 148 — guia dupla + 2 montantes + 2 chapas cada face", obs: "Maior desempenho acústico" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "Parede shaft — estrutura para encapsulamento de prumadas", obs: "Alçapão obrigatório para acesso" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "Parede hidrofugada (chapa RU) — banheiros e lavanderia", obs: "Revestimento cerâmico sobre RU" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "Parede acústica com lã mineral 50 ou 70mm", obs: "Rw mínimo por ambiente — NBR 15575" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "DRY", txt: "Tabela de tipos: código, composição, espessura total, Rw (dB)" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "ARQ", txt: "Forro de gesso liso — pendurais, espaçamento, alturas" },
    { z: "dry", c: "Tipos de Parede", tp: "exec", tg: "ARQ", txt: "Forro drywall com instalações — alçapões locados" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para TV — chapa 4mm ou OSB — todos os dormitórios e sala", obs: "Posição e dimensões na planta" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para louças sanitárias — bacia e lavatório", obs: "Compatível com projeto de interiores" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para barras de apoio PCD (quando aplicável)" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para armários fixos — cozinha, lavanderia, home office" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para espelhos acima de 0,60m × 0,60m" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para split — suporte interno e externo por ambiente" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para QDL — abertura e estrutura do nicho do quadro" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para boxe de vidro — perfil e dobradiça fixos" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Reforço para toalheiro, saboneteira e papel higiênico" },
    { z: "dry", c: "Reforços", tp: "exec", tg: "DRY", txt: "Chumbadores e parafusos especificados por tipo e substrato" },
    { z: "dry", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Pontos elétricos nas paredes drywall — alturas padrão NBR 5410" },
    { z: "dry", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Nichos para QDL — abertura correta no drywall" },
    { z: "dry", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Caixas elétricas 4×4 e 4×2 compatibilizadas com espessura" },
    { z: "dry", c: "Compat. Elétrica", tp: "exec", tg: "ELE", txt: "Posição das luminárias embutidas no forro" },
    { z: "dry", c: "Compat. Elétrica", tp: "exec", tg: "LMT", txt: "Esperas de LED nas sancas compatibilizadas com drywall" },
    { z: "dry", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Shaft de prumadas HID encapsulado — alçapão obrigatório" },
    { z: "dry", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Passagem de tubulações internas compatibilizada" },
    { z: "dry", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Dreno de AC na parede — canaleta ou tubo embutido" },
    { z: "dry", c: "Compat. Hidráulica", tp: "exec", tg: "HID", txt: "Ramal de gás no shaft — requisitos de ventilação" },
    { z: "dry", c: "Compat. Clima", tp: "exec", tg: "CLI", txt: "Nicho de split — dimensões do suporte e passagem de tubulação" },
    { z: "dry", c: "Compat. Clima", tp: "exec", tg: "CLI", txt: "Duto de exaustão de banheiros internos pelo forro", obs: "Diâmetro, caminhamento e saída especificados" },
    { z: "dry", c: "Compat. Clima", tp: "exec", tg: "MEC", txt: "Caixa de exaustão no forro — abertura e alçapão" },
    { z: "dry", c: "Compat. Telecom", tp: "exec", tg: "TEL", txt: "Pontos de TV, internet e telefone nas paredes drywall" },
    { z: "dry", c: "Compat. Telecom", tp: "exec", tg: "TEL", txt: "Pontos de automação e sensores nos dormitórios e sala" },
    { z: "dry", c: "Compat. Telecom", tp: "exec", tg: "TEL", txt: "Conduit dentro do drywall — DN mínimo 25mm" },
    { z: "dry", c: "Compat. Telecom", tp: "exec", tg: "AUT", txt: "Painéis de automação — profundidade do nicho" },
    { z: "dry", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Sprinklers no forro — abertura e detalhe do bocal", obs: "Espaçamento máximo — ABNT 13714" },
    { z: "dry", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Detectores de fumaça no forro — posição e compat." },
    { z: "dry", c: "Compat. PPCI", tp: "exec", tg: "PCI", txt: "Vedação corta-fogo nas passagens de tubulação", obs: "Golas intumescentes por DN" },
    { z: "dry", c: "Compat. Interiores", tp: "exec", tg: "AIT", txt: "Paredes compat. com projeto AIT — nichos e sancas", obs: "Verificar profundidade com projeto AIT" },
    { z: "dry", c: "Compat. Interiores", tp: "exec", tg: "AIT", txt: "Revestimentos especiais sobre drywall — carga e reforço" },
    { z: "dry", c: "Compat. Interiores", tp: "exec", tg: "AIT", txt: "Sancas e rebaixos de gesso — corte com posição de LED" },
    { z: "dry", c: "Aberturas", tp: "exec", tg: "ARQ", txt: "Vãos de portas — largura + folga para batente" },
    { z: "dry", c: "Aberturas", tp: "exec", tg: "DRY", txt: "Vergas drywall — montante duplo ambos os lados" },
    { z: "dry", c: "Aberturas", tp: "exec", tg: "ARQ", txt: "Contramarcos especificados por tipo de porta" },
    { z: "dry", c: "Aberturas", tp: "exec", tg: "ARQ", txt: "Nichos decorativos — dimensões e composição" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Juntas de controle a cada 10m ou em mudanças de plano" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Gaxeta acústica na guia inferior e superior" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Fita telada e massa nas juntas entre chapas" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Selante acrílico perimetral — parede × teto e piso" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Lã mineral — espessura e densidade especificadas" },
    { z: "dry", c: "Vedações e Acústica", tp: "exec", tg: "DRY", txt: "Rw mínimo por ambiente — NBR 15575" },
    { z: "dry", c: "Forros", tp: "exec", tg: "DRY", txt: "Planta de forro cotada com alturas por ambiente" },
    { z: "dry", c: "Forros", tp: "exec", tg: "DRY", txt: "Tipos: liso, com sanca, rebaixado, curvo — tabela de tipos" },
    { z: "dry", c: "Forros", tp: "exec", tg: "DRY", txt: "Pendurais — diâmetro, espaçamento, fixação na laje" },
    { z: "dry", c: "Forros", tp: "exec", tg: "DRY", txt: "Alçapões de manutenção locados sobre cada shaft" },
    { z: "dry", c: "Documentação", tp: "exec", tg: "ARQ", txt: "Memorial descritivo — todos os sistemas" },
    { z: "dry", c: "Documentação", tp: "exec", tg: "DRY", txt: "Quantitativo de chapas por tipo e ambiente (m²)" },
    { z: "dry", c: "Documentação", tp: "exec", tg: "DRY", txt: "Quantitativo de perfis — montantes e guias (m linear)" },
    { z: "dry", c: "Documentação", tp: "exec", tg: "DRY", txt: "Lista de reforços por unidade e localização" },
    { z: "dry", c: "Documentação", tp: "exec", tg: "ARQ", txt: "ART ou RRT do responsável técnico" },

    // Drywall (dry) - bim
    { z: "dry", c: "Famílias e Tipos", tp: "bim", tg: "BIM", txt: "Tipos de parede multicamada com composição exata", obs: "m² por material: chapa, lã, revestimento" },
    { z: "dry", c: "Famílias e Tipos", tp: "bim", tg: "BIM", txt: "Rw (dB) e fabricante associados ao tipo de parede" },
    { z: "dry", c: "Famílias e Tipos", tp: "bim", tg: "BIM", txt: "Categorias BIM corretas para export de quantitativos" },
    { z: "dry", c: "Reforços BIM", tp: "bim", tg: "BIM", txt: "Reforços modelados fisicamente — não como texto" },
    { z: "dry", c: "Reforços BIM", tp: "bim", tg: "BIM", txt: "Schedule de reforços por unidade extraível do modelo" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "MEP", txt: "Clash: drywall × instalações elétricas — caixas e eletrodutos" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "MEP", txt: "Clash: drywall × instalações hidráulicas" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "MEP", txt: "Clash: drywall × dutos de climatização e exaustão" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "MEP", txt: "Clash: forro × sprinklers, luminárias e detectores" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "MEP", txt: "Shafts com encapsulamento correto e alçapão posicionado" },
    { z: "dry", c: "Clash Detection", tp: "bim", tg: "PCI", txt: "Vedação corta-fogo modelada nas passagens pelo shaft" },
    { z: "dry", c: "Quantitativos BIM", tp: "bim", tg: "BIM", txt: "Schedule de chapas por tipo — m² por ambiente e total" },
    { z: "dry", c: "Quantitativos BIM", tp: "bim", tg: "BIM", txt: "Schedule de perfis — m linear por tipo" },
    { z: "dry", c: "Quantitativos BIM", tp: "bim", tg: "BIM", txt: "Schedule de lã mineral — m² por espessura" },
    { z: "dry", c: "Quantitativos BIM", tp: "bim", tg: "BIM", txt: "Schedule de reforços — unidades por tipo" },
    { z: "dry", c: "Quantitativos BIM", tp: "bim", tg: "BIM", txt: "Schedule de esquadrias com parâmetros completos" }
];

export const CATEGORIES: Record<string, { exec: string[]; bim: string[] }> = {
    gar: {
        exec: ["Cotas e Geometria", "Tabela de Vagas", "Níveis e Caimentos", "Estrutura", "Pintura de Pilares", "Sinalização Horizontal", "Sinalização Vertical", "Detalhamentos", "Compat. PPCI", "Compat. Hidráulica", "Compat. Elétrica", "Compat. Telecom", "Compat. Mecânica", "Acabamentos"],
        bim: ["Geometria e Vagas", "Pilares e Sinalização", "Suportes MEP", "Caimentos e Juntas", "Quantitativos"]
    },
    lixo: {
        exec: ["Layout", "Revestimentos", "Hidrossanitário", "Esquadrias", "Proteção", "Níveis", "Instalações"],
        bim: ["Conexões", "Esquadrias BIM", "Quantitativos"]
    },
    dry: {
        exec: ["Planta e Locação", "Tipos de Parede", "Reforços", "Compat. Elétrica", "Compat. Hidráulica", "Compat. Clima", "Compat. Telecom", "Compat. PPCI", "Compat. Interiores", "Aberturas", "Vedações e Acústica", "Forros", "Documentação"],
        bim: ["Famílias e Tipos", "Reforços BIM", "Clash Detection", "Quantitativos BIM"]
    }
};
